"""Build the committed walkthrough and record the verified dependency snapshot."""
from pathlib import Path
import importlib.metadata as im
import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]
nb = nbf.v4.new_notebook()
md, code = nbf.v4.new_markdown_cell, nbf.v4.new_code_cell
nb.cells = [
    md("# Transcriptomic Profiling of Oral Squamous Cell Carcinoma\n\nAn auditable reanalysis of **GSE20116**, three matched tumor–normal pairs. This notebook reads genuine pipeline results. Synthetic fixtures exist only under `tests/fixtures`. See [REPORT.md](../REPORT.md) for the research interpretation and [provenance](../data/PROVENANCE.md) for source details."),
    md("## 1. Reproduce or load the analysis\nInstall this project with Python 3.11, then run `oscc run` from the repository root. Subsequent runs can use `oscc run --offline`. This notebook reuses completed results to avoid unnecessarily refitting; uncomment the explicit pipeline call to repeat the computation. No dataset substitutions occur."),
    code("from pathlib import Path\nimport os\nimport pandas as pd\nimport numpy as np\nROOT = Path.cwd()\nif ROOT.name == 'notebooks':\n    ROOT = ROOT.parent\nassert (ROOT / 'pyproject.toml').exists(), 'Run from the repository or notebooks directory'\nos.environ.setdefault('MPLCONFIGDIR', str(ROOT / '.tools/matplotlib'))\nfrom oscc.dashboard import load_results\n# from oscc.pipeline import run\n# run(ROOT, offline=True)  # Requires the cached original sources and GMT.\nbundle = load_results(ROOT)\nbundle['manifest']['summary']"),
    md("## 2. Check the source and pairing\nGEO supplies legacy MAX alignments. The original paper's Table S1 contains separate raw and normalized columns. The parser explicitly selects raw sums in columns D–I. The cached workbook and GEO SOFT file are checksum-verified by the acquisition command. If raw sources are not yet cached, run `oscc download`. Missing age, sex, stage and HPV fields are not imputed."),
    code("metadata = bundle['metadata']\nmetadata[['patient_id', 'condition', 'source_column', 'tissue', 'sample_url']]"),
    code("from oscc.validation import validate_counts, design_matrix\ncounts, metadata = validate_counts(bundle['counts'], metadata)\ndesign = design_matrix(metadata)\nprint('Genes x samples:', counts.shape)\nprint('Design rank:', np.linalg.matrix_rank(design), '; residual df:', len(metadata) - design.shape[1])\ndesign"),
    md("## 3. Preprocessing and normalization\nThe source table was already filtered by its authors. Representatives are selected by maximum exon count, with lexical RefSeq tie-breaking; overlapping isoforms are never summed. An additional abundance-only rule requires at least 10 reads in at least three libraries. The full filter/mapping audits remain available. Raw counts enter the count model; median-of-ratios normalized counts and log2(normalized + 1) serve different purposes. The log transform is not a VST."),
    code("filter_audit = pd.read_csv(ROOT / 'results/tables/filter_audit.csv')\nprint(filter_audit.retained.value_counts())\nnormalized = bundle['normalized_counts']\nlog_expression = bundle['log_expression']\nassert np.allclose(log_expression, np.log2(normalized + 1))\npd.read_csv(ROOT / 'results/tables/library_sizes.csv')"),
    md("## 4. Quality control\nPCA uses centered, unscaled log normalized expression of the 2,000 most variable genes. It is not fitted on DE-selected genes. Lines link matched patients; no samples were removed based on plot appearance. Raw-read QC has not been recomputed."),
    code("from IPython.display import Image, display\ndisplay(Image(filename=str(ROOT / 'results/figures/pca.png'), width=700))\nbundle['manifest']['qc']"),
    md("## 5. Paired differential expression\nPyDESeq2 uses `~ patient_id + condition`, with a tumor/normal Wald contrast. The fit retains convergence flags and excludes failed fits from BH-adjusted calls. No source-publication p-values are reused. The nominal null is LFC = 0; the absolute LFC cutoff is an additional selection rule, not a threshold-null hypothesis test."),
    code("from oscc.differential import classify\nresults = bundle['differential_expression']\ncalls = classify(results, alpha=.05, lfc=1.)\nprint(calls.value_counts())\nprint(bundle['manifest']['diagnostics'])\nresults.loc[calls != 'not_significant'].sort_values('padj').head(10)"),
    code("display(Image(filename=str(ROOT / 'results/figures/volcano.png'), width=800))"),
    md("## 6. Inspect a real candidate\nThe selected gene below is chosen from the computed results, not supplied as a presumed cancer marker. Compare each patient's normalized measurements and note that expression differences do not imply causality."),
    code("from oscc.dashboard import gene_expression\ncandidate = results.loc[results.padj.notna()].sort_values('padj').index[0]\nprint(candidate)\ngene_expression(bundle, candidate)"),
    md("## 7. Pathway enrichment\nPreranked GSEA uses signed Wald statistics and 1,000 gene-set permutations with seed 42. Positive NES points toward tumor-upregulated genes. ORA uses significant up/down lists and the tested-gene background. GSEA FDR and ORA BH values are different corrections. Terms are displayed regardless of significance; zero permutation estimates are resolution-limited. Historical symbols are matched exactly; unmatched symbols are audited."),
    code("gsea = bundle['gsea']\ngsea.sort_values('padj')[['Term', 'NES', 'pvalue', 'padj', 'genes']].head(10) if not gsea.empty else 'No enrichment results; see manifest status'"),
    code("ora = bundle['ora']\nora.sort_values('padj').head(10) if not ora.empty else 'No eligible ORA results'"),
    md("## 8. Interpretation and next steps\nThree patients leave only two residual degrees of freedom. Historical technology, source prefiltering, representative-transcript selection, incomplete annotation and tissue-composition differences restrict interpretation. Same-cohort agreement with Tuch et al. is not independent replication. Validate candidates in an independent anatomically matched OSCC cohort and with appropriately designed qPCR or perturbation experiments. Read the generated report and figure captions before quoting results.\n\nLaunch the interactive explorer with `streamlit run app/streamlit_app.py`.\n\nReferences: [Tuch et al.](https://doi.org/10.1371/journal.pone.0009317), [DESeq2](https://doi.org/10.1186/s13059-014-0550-8), [PyDESeq2](https://doi.org/10.1093/bioinformatics/btad547), [GSEApy](https://doi.org/10.1093/bioinformatics/btac757)."),
]
nb.metadata = {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}, "language_info": {"name": "python", "version": "3.11"}}
nbf.write(nb, ROOT / "notebooks/01_oscc_analysis.ipynb")
packages = sorted(d.metadata["Name"] + "==" + d.version for d in im.distributions() if d.metadata["Name"].lower() not in ["oscc-transcriptomics", "pip", "setuptools"])
(ROOT / "requirements-lock.txt").write_text("# Verified Python 3.11 Windows environment snapshot.\n# Other platforms may resolve additional platform-specific packages.\n" + "\n".join(packages) + "\n", encoding="utf-8")
